# Generated by Django 5.1.7 on 2025-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0005_alter_rating_user_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="moduleinstance",
            name="semester",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="moduleinstance",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="professor",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="professor",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="professor",
            name="prof_id",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
